brantburnett/couchbase-index-manager

README.md, app/create-index-mutation.js, app/index-definition.js, app/sync.js
Motivation
----------
Automatic replica management on Couchbase 5.X still has some limitations
surrounding replica scaling, and 5.0/5.1 have limitations around replica
movement.  Some clusters may require the more granular control of
manually created replicas.
Modifications
-------------
Allow each definition to choose manual_replica mode, and leave this mode
always on for Couchbase 4.X.
Results
-------
More fine grained control of indexes on Couchbase Server 5.X, if
desired.
=> Use manual replicas on Couchbase 5.X clusters

README.md, app/node-map.js, app/sync.js, example/beer-sample/default.yaml
Motivation
----------
Allow nodes on index definitions to be defined using aliases, which may
then be varied per environment.
Modifications
-------------
Added the nodeMap definition type.
=> Add node maps to definitions

app/index-definition.js, app/index-manager.js
Motivation
----------
Supporting node assignment updates requires information about what nodes
the index currently resides on.
Modifications
-------------
Collect and return this information as part of getIndexes in
IndexManager.
Results
-------
Node assignment information is available for use by the IndexDefinition.
=> Issue #14: Get node info from Couchbase

app/connection-manager.js, app/index-definition.js, app/index-manager.js, app/sync.js
Motivation
----------
To use ALTER INDEX statements we must ensure that the cluster version is
at least 5.5.
Modifications
-------------
Use /default/pools to get the list of nodes and select the lowest
clusterCompatability to determine the effective cluster version.
Pass this value through to the index definition to determine mutations.
Also use this value instead of the --no-rbac flag to recognize we're on
a 4.0 cluster and force manual replica management.
Results
-------
Cluster version is now available for use for replica management in
future commits.
Additionally, we are now compatible with 5.0 clusters that are still
running with authentication disabled.
=> Issue #14: Make cluster version available

app/connection-manager.js, app/index-manager.js, app/sync.js
Motivation
----------
Getting index statuses is not working on pre-5.0 clusters because it
requires authentication though other operations do not.
Modifications
-------------
Use a ClusterManager instead of BucketManager for cluster level admin
API requests.
Results
-------
Admin API calls now succeed on both 4.0 and 5.0 clusters.
=> Issue #14: Handle pre-5.0 admin API auth

README.md, app/cli.js, app/feature-versions.js, app/index-definition.js, app/index-manager.js, app/index-mutation.js, app/move-index-mutation.js, app/plan.js, app/sync.js, app/update-index-mutation.js, package-lock.json, package.json, test/index-definition.spec.js, test/plan.spec.js
Motivation
----------
Support changes to index node assignments after an index is created.
Modifications
-------------
Implemented a phase system for mutations so that different replicas can
be moved separately to prevent downtime.
Fixed a flaw in the logic using the /indexStatus API to retrieve node
assignments for automatic replicas.
Created MoveIndexMutation to handle ALTER INDEX statements on 5.5, with
support in IndexManager.
Created a FeatureVersion class to help manage Couchbase versions where
specific features are supported.
Return proper mutations for changes to nodes and num_replicas, in both
the manual and automatic index mutation forms.
Change UpdateIndexMutation to recognize when it's actually a safe
mutation based on replicas being present.
Results
-------
Automatic replica …
=> Issue #14: Update index node assignments

app/update-index-mutation.js
Motivation
----------
Updating manual replicas is showing nodes for all replicas, not just the
specific replica being updated.
Modifications
-------------
Use withClause so that the display is for the specific nodes on this
update.
Show both the current and new node assignments.
Results
-------
Information is now accurate.
=> Issue #21: Correct update node format for manual replicas

README.md, app/index-definition.js, app/index-manager.js, app/sync.js, example/beer-sample/default.yaml, test/index-definition.spec.js
Motivation
----------
Reduce occurences of index updates when there aren't actually any index
changes by normalizing index_key and condition using the same approach
as Couchbase.
Modifications
-------------
Instead of normalizing as the index definition is built, normalize once
(and asynchronously) before generating mutations.
Perform normalization by using EXPLAIN to get the query plan for
creating the index and analyzing the output plan.
Results
-------
index_key and condition are now prenormalized by Couchbase before
comparing to the existing index, preventing unnecessary index updates.
=> Issue #24: Use Couchbase to perform index def normalization

.dockerignore, README.md, app/create-index-mutation.js, app/feature-versions.js, app/index-definition.js, app/sync.js, app/update-index-mutation.js, test/index-definition.spec.js
Motivation
----------
Support Couchbase Server 5.5 horizontal index partitioning.
Modifications
-------------
Add `partition` attribute to the index definition hash which allows
definitions to include partition attributes and strategy.
Reject if version <5.5 or strategy != HASH (the only supported strategy
currently).
Issue update index mutations if the partition definition is changed.
Results
-------
Basic partitions without replicas are supported.  Behavior with replicas
is currently undefined and will be addressed in an upcoming commit.
=> Issue #25: Initial support for index partitioning

README.md, app/index-definition.js, test/index-definition.spec.js
Motivation
----------
Couchbase Server 5.0 allows sorting any index_key in descending rather
than ascending order.
Modifications
-------------
When normalizing index_key use the `desc` boolean to correctly update
the statement.
Results
-------
For CB >= 5.0 any index_key may have DESC appended in the definition.
For CB < 5.0 an error will be thrown if DESC is encountered.
=> Issue #27: Support for descending collation

app/create-index-mutation.js
Motivation
----------
Allow operator to review the assigned nodes from the plan prior to
executing the plan.
Modifications
-------------
Append the assigned nodes, if any, to the plan output for create index
mutations.
Results
-------
Operators can now see node assignments, when present.
=> Issue #30: Include node list on create index plan output

app/index-definition.js, app/index-manager.js, example/beer-sample/default.yaml, test/index-definition.spec.js
Motivation
----------
Extend support for partitioned replicas on Couchbase Server 5.5 to
include replicas.
Modifications
-------------
Decouple num_replica and nodes list length for partitioned replicas.
Handle partitioned indexes differently when getting the list of nodes
for existing indexes, as each replica will have the same node list.
Prevent manual_replica from being used for partitioned indexes.
Couchbase internals for partioned indexes really need to use automatic
replicas so Couchbase can ensure partitions are kept on different nodes
for each replica.
Results
-------
Partitioned replicas are now supported with automatic replica
management.
There is a bug in Couchbase 5.5 Beta which will result in errors if you
specify both a list of nodes and a value for num_replica for a …
=> Issue #27: Support for replicas on partitioned indexes

app/plan.js, test/plan.spec.js
Motivation
----------
In some cases with partitioned indexes and replicas all index nodes are
not ready to build indexes immediately.  Issuing the BUILD INDEX command
can then cause them to only partially build at first.
Modifications
-------------
Add a 3 second delay between creating all indexes and issuing the BUILD
INDEX command.
Results
-------
Race conditions should be significantly reduced.
=> Issue #35: Reduce index build race conditions

.travis.yml, app/index-definition.js
Motivation
-------------
WHERE clause was being added before the PARTITION clause in cases where both were used, causing invalid N1QL to be generated.
Modifications
------------------
Moved the addition of the WHERE clause to be after the PARTITION clause (if any) is added.
=> Reverse order of PARTITION and WHERE clauses

app/definition-loader.js, app/sync.js
Motivation
----------
Allow definition loading to be used by other processes in future work,
such as definition validation.
Modifications
-------------
Moved definition loading logic from sync.js to definition-loader.js.
=> Separate definition loading from sync class

app/definition-loader.js, app/index-definition.js, app/node-map.js
Motivation
----------
Help support a future "validate" command to allow CI tools to validate
index definitions as they are committed to source control.
Modifications
-------------
Add index definition property validates to index-definition.js and
node-map.js.  Use these validators during the load process in
definition-loader.js.
=> Validate index definitions as they are loaded

.vscode/launch.json, README.md, app/cli.js, app/validator.js
Motivation
----------
Allow CI tooling to validate index definition syntax.
Modifications
-------------
Added validate command to cli.js, and validator.js to perform the
validation process.
Results
-------
Index definitions can be validated.  For more complete validation,
--validate-syntax argument will validate the generated N1QL statements
against a Couchbase cluster.
=> Add validate command line syntax

app/create-index-mutation.js, app/index-definition.js, app/index-manager.js, app/update-index-mutation.js, example/beer-sample/default.yaml, test/index-definition.spec.js
Motivation
----------
Including retain_deleted_xattr in the WITH clause is desirable for
Sync Gateway support.
Modifications
-------------
Include retain_deleted_xattr in the index definition, and apply it to
the with clause when true. Also include it in the index change logic to
drop/recreate the index.
Closes #53
=> Add support for retain_deleted_xattr

.eslintrc.yml, README.md, app/cli.js, app/create-index-mutation.js, app/index-definition.js, app/index-manager.js, app/update-index-mutation.js, test/index-definition.spec.js
Motivation
----------
Allow the number of partitions in a partitioned index to be manually
controlled.
Modifications
-------------
Added an option to the partition definition to control the number of
partitions. If missing, the number is ignored. If present, the index
is synchronized to have that number of partitions.
Fixed a bug in SDK 3.x upgrade that prevented partitioned indexes from
working as expected.
Closes #52
=> Add support for num_partition

app/feature-versions.js, app/index-definition.js, app/index-manager.js, app/resize-index-mutation.js, test/index-definition.spec.js
Motivation
----------
Allow the number of replicas for an existing index to be changed without
downtime using the ALTER INDEX statement on Couchbase Server 6.5.
Modifications
-------------
Add ResizeIndexMutation and wire it up to be used whenever the Couchbase
server is on at least version 6.5.
Results
-------
Safe changes with no index downtime are performed if the number of
replicas is changed and the server is on 6.5 of later. No changes to
behavior for older Couchbase Server versions.
Close #56
=> Add support for ALTER INDEX replica_count

.travis.yml, Dockerfile, app/index-definition.js, env/Up.ps1, example/beer-sample/default.yaml, package-lock.json
Motivation
----------
We shouldn't require the index definition details for indices being
dropped.
Modifications
-------------
Accept dropped indices with only a name attribute.
Update to NPM lockfile v2.
Improve some local test scripts.
Fixes #67
=> Loosen validation requirements for dropped indices

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .editorconfig, .env, .gitignore, .npmignore, package-lock.json, package.json
=> Support dev containers

.devcontainer/docker-compose.yml, app/definition/index-definition.spec.ts, app/definition/index-definition.ts, app/index-manager.ts, app/plan/plan.ts, example/travel-sample/default.yaml
Motivation
------------
Scopes and collections allow indexes with the same name across different
collections.
Modifications
---------------
Normalize the API responses for scope/collection information, and when
matching an index ensure we account for the scope/collection.
When building indices or waiting for the build to complete, target a specific
scope/collection (or default).
Add travel-sample to the dev environment since it has scopes/collections.
Results
--------
couchbase-index-manager is now compatible with scopes/collections in Couchbase
Server 7.0. The presense of indices within a collectdion will no longer confuse it.
However, it isn't yet capable of managing indices in a collection.
=> Avoid name conflicts with scope/collections

app/plan/create-index-mutation.ts, app/plan/drop-index-mutation.ts, app/plan/index-mutation.ts, app/plan/move-index-mutation.ts, app/plan/plan.ts, app/plan/resize-index-mutation.ts, app/plan/update-index-mutation.ts
Motivation
----------
This is a step in the process of supporting scopes/collections, allowing
index planning to take into account scopes/collections.
Modifications
-------------
Include scope/collection in the plan display if non-default.
Group index building by scope/collection.
Include the scope/collection in index drops.
=> Add collection support to plans

.vscode/launch.json, app/configuration/index-validation.ts, app/configuration/types.ts, app/definition/definition-loader.ts, app/definition/index-definition-base.ts, app/definition/index-definition.ts, app/plan/index-mutation.ts, app/util.ts, example/travel-sample/default.yaml
Motivation
----------
Manage indexes on scopes/collections.
Modifications
-------------
Allow indexes to define scope and collection attributes, and use these
when comparing to existing indexes and creating/updating/dropping
indexes
Results
-------
Basic scope/collection support is in place. However, replica management
with resizing and moving is not yet supported.
=> Complete basic collection support

app/definition/index-definition.spec.ts, app/definition/index-definition.ts, app/feature-versions.ts, app/plan/move-index-mutation.ts, app/sync.ts, app/validator.ts
Motivation
----------
Couchbase 5.5 is pretty old at this point, so the added complexity of
supporting 4.x and 5.0 isn't very valuable.
Modifications
-------------
Remove special controls in place to support older versions of Couchbase.
- Automatic replica management is now always supported
- Moving index replicas with automatic replica management is now always
supported
- Partitioned indexes are now always supported
- RBAC is always used for authentication (this was done in a previous
change)
=> Remove support for old Couchbase versions

.devcontainer/docker-compose.yml, packages/couchbase-index-manager/app/index-manager.ts
Motivation
------------
There seems to be a bug around index resizing and prepared queries,
https://issues.couchbase.com/browse/MB-53264, this prevents that issue and
possibly other unexpected issues. It should also be slightly
more performant by avoiding an unused prepare, since every
query is different.
Note that this is only required until 4.1.2 of the SDK fixes this bug:
https://issues.couchbase.com/browse/JSCBC-1092
Modifications
---------------
- Send all index mutations with adhoc of true.
- Update to Server 7.1.1 for local testing
=> Run all index mutation queries as adhoc

package-lock.json, packages/couchbase-index-manager/app/index-manager.ts, packages/couchbase-index-manager/package.json
Motivation
------------
The latest Couchbase SDK is getting errors where we were accessing an
internal member to make HTTP requests.
Modifications
---------------
Use the new surface that is a bit less hacky, though still involves accessing an
unexported file from the SDK.
Fixes #118
=> Use new method to get HttpExecutor

packages/couchbase-index-manager/app/connection-manager.ts, packages/couchbase-index-manager/app/definition/index-definition.spec.ts, packages/couchbase-index-manager/app/definition/index-definition.ts, packages/couchbase-index-manager/app/index-manager.ts, packages/couchbase-index-manager/app/sync.ts
Motivation
----------
Couchbase Capella uses port 18091 to represent index nodes, but we
normalize to port 8091 to compare the node list if no port is
specified.
Modifications
-------------
When connecting via the "couchbases" secure protocol, assume that index
nodes use 18091 when normalizing.
=> Match secure port numbers

packages/couchbase-index-manager/app/definition/index-definition.spec.ts, packages/couchbase-index-manager/app/definition/index-definition.ts, packages/couchbase-index-manager/app/plan/create-index-mutation.ts, packages/couchbase-index-manager/app/plan/resize-index-mutation.ts, packages/couchbase-index-manager/app/plan/update-index-mutation.ts
Motivation
----------
Capella defaults num_replica to 1 while Couchbase Server defaults to 0.
Allowing num_replica to be undefined allows the user to use the default
for their environment.
Modifications
-------------
Allow num_replica to be undefined and don't send in the index create
or update query if it is undefined. Don't consider num_replica when
resizing existing indices if it is undefined.
Results
-------
We are now more compatible with Capella behaviors. However, there is
still one remaining issue. Capella will ignore num_replica = 0 on
create and still create an index with one replica, causing the next
sync to resize to zero replicas. However, num_replica = undefined will
now behave consistently.
=> Allow num_replica to be undefined
